name: ClashForge

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    paths:
      - '.github/workflows/ClashForge.yml'
      - 'ClashForge.py'
      - 'requirements2.txt'
      - 'GeoLite2-Country.mmdb'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  INPUT: ${{ vars.INPUT }}
  GEOLITE_VERSION: 2025.09.04
  GEOLITE_URL: https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.09.04/GeoLite2-Country.mmdb
  GEOLITE_SHA256: 8d07f7a8ca9d96b9e0dd8fa6d08683f34fbc8ecadbd75990b465b6d4d160d3ad

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmaxminddb-dev
        continue-on-error: false

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          echo "geoip2==2.9.0" > requirements2.txt
          echo "playwright==1.48.0" >> requirements2.txt
          echo "httpx==0.27.0" >> requirements2.txt
          echo "pyyaml==6.0.1" >> requirements2.txt
          echo "requests==2.31.0" >> requirements2.txt
          echo "psutil==5.9.8" >> requirements2.txt
          pip install -r requirements2.txt
          playwright install --with-deps
        continue-on-error: false

      - name: Verify GeoLite2-Country.mmdb
        run: |
          if [ -f GeoLite2-Country.mmdb ]; then
            echo "Found GeoLite2-Country.mmdb, verifying SHA256..."
            computed_sha256=$(sha256sum GeoLite2-Country.mmdb | awk '{print $1}')
            if [ "$computed_sha256" = "${{ env.GEOLITE_SHA256 }}" ]; then
              echo "GeoLite2-Country.mmdb is up-to-date (version ${{ env.GEOLITE_VERSION }})"
            else
              echo "GeoLite2-Country.mmdb is outdated, downloading version ${{ env.GEOLITE_VERSION }}..."
              rm -f GeoLite2-Country.mmdb
              wget -O GeoLite2-Country.mmdb "${{ env.GEOLITE_URL }}"
            fi
          else
            echo "GeoLite2-Country.mmdb not found, downloading version ${{ env.GEOLITE_VERSION }}..."
            wget -O GeoLite2-Country.mmdb "${{ env.GEOLITE_URL }}"
          fi
          ls -l GeoLite2-Country.mmdb
          computed_sha256=$(sha256sum GeoLite2-Country.mmdb | awk '{print $1}')
          if [ "$computed_sha256" != "${{ env.GEOLITE_SHA256 }}" ]; then
            echo "Error: Downloaded GeoLite2-Country.mmdb SHA256 mismatch!"
            exit 1
          fi
        continue-on-error: false

      - name: Cache test results
        uses: actions/cache@v3
        with:
          path: |
            speed_cache.json
            exclusion_cache.json
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Run ClashForge.py
        run: |
          for i in {1..3}; do
            python ClashForge.py && break
            echo "Retry $i failed, waiting 5s..."
            sleep 5
          done
        continue-on-error: false

      - name: Debug file status
        run: |
          echo "Listing files after running ClashForge.py:"
          ls -l
          echo "Checking content of clash_config.yaml (if exists):"
          cat clash_config.yaml || echo "clash_config.yaml not found"
          echo "Checking content of clash_config.yaml.json (if exists):"
          cat clash_config.yaml.json || echo "clash_config.yaml.json not found"
          echo "Checking content of exclusion_cache.json (if exists):"
          cat exclusion_cache.json || echo "exclusion_cache.json not found"
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "update: Auto-generated by ClashForge (GeoLite2 ${{ env.GEOLITE_VERSION }})"
          else
            echo "No changes detected, creating an empty commit."
            git commit --allow-empty -m "update: No changes detected (GeoLite2 ${{ env.GEOLITE_VERSION }})"
          fi
          git clean -fd
          for i in {1..3}; do
            echo "Attempt $i to pull, rebase, and push..."
            git fetch origin
            git rebase origin/main
            if [ $? -eq 0 ]; then
              git push origin main
              if [ $? -eq 0 ]; then
                echo "Push successful on attempt $i."
                exit 0
              fi
            else
              echo "Rebase failed, attempting to merge..."
              git rebase --abort
              git merge origin/main --no-edit
              git add .
              git commit -m "merge: Resolve conflicts and update (GeoLite2 ${{ env.GEOLITE_VERSION }})" || true
              git push origin main
              if [ $? -eq 0 ]; then
                echo "Push successful after merge on attempt $i."
                exit 0
              fi
            fi
            sleep 5
          done
          echo "Failed to push after multiple attempts."
          exit 1
        continue-on-error: false

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number || 1,
              body: `ClashForge workflow failed. Please check the logs for details.`
            })
